version: '3.4'
services:

  laravel:
    container_name: laravel
    image: localbuild/laravel-docker:${DOCKER_TAG}
    build:
     context: .
     dockerfile: ubuntu/Dockerfile
     args:
       LARAVEL_VERSION: ${LARAVEL_VERSION}
       DOCKER_IMAGE_VERSION: ${DOCKER_IMAGE_VERSION} 
       PGSQL_DEP: ${PGSQL_DEP} 
       PDO: ${PDO} 
       DB: ${DB}
       PHP_VERSION: ${PHP_VERSION} 
       PHP_SHA256: ${PHP_SHA256} 
       GPG_KEYS: ${GPG_KEYS} 
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=laravel
      - LARAVEL_DB_HOST=mysql
      - FORCE_MIGRATE=force
    command: [ "php", "artisan", "serve", "--host=0.0.0.0", "--port=3000" ]
    ports: 
      - 3000:3000