name: Laravel CI

on:
  push:
    branches:
    - master
    - laravel-php73
    - laravel-php74
  pull_request:
    branches:
    - master
    - laravel-php73
    - laravel-php74

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose -f docker-compose.yml-ci build --pull --no-cache
    - name: Bringup the environment
      run: docker-compose -f docker-compose.yml-ci --env-file .env up -d
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: List all containers
      run: docker ps -a
    - name: Testing connection to laravel
      run: docker-compose -f docker-compose.yml-ci exec -T laravel curl --retry 10 --retry-connrefused -I http://localhost:3000